from .base_agent import BaseAgent
from tools.crm_tool import CRMTool
from knowledge_base.rag import RAGSystem


class SalesAgent(BaseAgent):

    name = "Sales Agent"

    description = "Handles sales, leads, follow-ups and orders"

    def __init__(self):
        self.crm_tool = CRMTool()
        self.rag = RAGSystem()

    def can_handle(self, request):

        sales_keywords = [
            "sales",
            "sale",
            "lead",
            "leads",
            "follow-up",
            "follow up",
            "followups",
            "customer",
            "customers",
            "order",
            "orders",
            "revenue",
            "sales policy",
            "sales sop",
            "sales process",
        ]

        request_lower = request.lower()

        return any(keyword in request_lower for keyword in sales_keywords)

    def get_required_permission(self, request):

        request_lower = request.lower()

        # ==========================================
        # Knowledge Base / Sales SOP Questions
        # ==========================================

        knowledge_keywords = [
            "policy",
            "sop",
            "process",
            "procedure",
            "how can",
            "how do",
            "how soon",
            "follow-up process",
            "follow up process",
        ]

        is_knowledge_question = any(
            keyword in request_lower for keyword in knowledge_keywords
        )

        if is_knowledge_question:
            return None

        if "lead" in request_lower:
            return "view_leads"

        if "customer" in request_lower:
            return "view_customers"

        if "order" in request_lower:
            return "view_orders"

        if "sales" in request_lower or "sale" in request_lower:
            return "view_sales"

        if "revenue" in request_lower:
            return "view_sales"

        return "view_sales"

    def process(self, request, user, credentials=None):

        request_lower = request.lower()

        # =====================================================
        # Extract CURRENT USER QUESTION
        # =====================================================

        if "current user question:" in request_lower:

            current_question = request_lower.split(
                "current user question:",
                1,
            )[1].strip()

        else:

            current_question = request_lower

        # =====================================================
        # Detect contextual request generated by orchestrator
        # =====================================================

        is_contextual_request = (
            "contextual agent request:" in request_lower
            or "previous conversation context:" in request_lower
            or "specific entity context:" in request_lower
        )

        # =====================================================
        # Identify contextual topic
        # =====================================================

        contextual_topic = None

        if is_contextual_request:

            # -----------------------------------------------
            # General Sales Status
            # IMPORTANT:
            # Check this BEFORE follow-ups/orders/leads.
            # -----------------------------------------------

            if (
                "current sales status" in request_lower
                or "sales status" in request_lower
                or "current sales summary" in request_lower
                or "sales summary" in request_lower
                or "current sales overview" in request_lower
                or "sales overview" in request_lower
                or "current sales information" in request_lower
                or "sales information" in request_lower
            ):
                contextual_topic = "sales_status"

            elif (
                "pending sales follow-up" in request_lower
                or "pending follow-up" in request_lower
                or "pending follow up" in request_lower
                or "customers requiring follow-up" in request_lower
                or "customers requiring follow up" in request_lower
            ):
                contextual_topic = "followups"

            elif (
                "orders discussed previously" in request_lower
                or "order discussed previously" in request_lower
                or "pending orders" in request_lower
                or "order details" in request_lower
            ):
                contextual_topic = "orders"

            elif (
                "new leads" in request_lower
                or "leads discussed previously" in request_lower
                or "lead details" in request_lower
                or "lead-by-lead" in request_lower
            ):
                contextual_topic = "leads"

            elif (
                "customers discussed previously" in request_lower
                or "customer details" in request_lower
                or "customer information" in request_lower
            ):
                contextual_topic = "customers"

        # =====================================================
        # Knowledge Base / Sales SOP Questions
        # =====================================================

        knowledge_keywords = [
            "policy",
            "sop",
            "process",
            "procedure",
            "how can",
            "how do",
            "how soon",
            "follow-up process",
            "follow up process",
        ]

        is_knowledge_question = any(
            keyword in current_question for keyword in knowledge_keywords
        )

        if is_knowledge_question:

            knowledge_answer = self.rag.generate_answer(request)

            if knowledge_answer:

                return {
                    "agent": self.name,
                    "status": "success",
                    "data": {
                        "knowledge_answer": knowledge_answer,
                    },
                    "message": knowledge_answer,
                }

        # =====================================================
        # Detect "Tell me more" / contextual detail request
        # =====================================================

        is_more_request = any(
            keyword in current_question
            for keyword in [
                "tell me more",
                "more details",
                "more information",
                "explain more",
                "describe them",
                "who are they",
                "which ones",
            ]
        )

        # =====================================================
        # CONTEXTUAL SALES STATUS
        #
        # Example:
        #
        # User:
        # What is our current sales status?
        #
        # User:
        # Tell me more.
        #
        # Return the complete sales summary instead of
        # falling into the pending follow-up handler.
        # =====================================================

        if is_more_request and contextual_topic == "sales_status":

            leads_result = self.crm_tool.execute(
                "get_leads",
                user,
            )

            followups_result = self.crm_tool.execute(
                "get_pending_followups",
                user,
            )

            customers_result = self.crm_tool.execute(
                "get_customers",
                user,
            )

            orders_result = self.crm_tool.execute(
                "get_orders",
                user,
            )

            leads_data = (
                leads_result.get("data", {})
                if leads_result.get("status") == "success"
                else {}
            )

            followups_data = (
                followups_result.get("data", {})
                if followups_result.get("status") == "success"
                else {}
            )

            customers_data = (
                customers_result.get("data", {})
                if customers_result.get("status") == "success"
                else {}
            )

            orders_data = (
                orders_result.get("data", {})
                if orders_result.get("status") == "success"
                else {}
            )

            total_leads = leads_data.get(
                "total_leads",
                0,
            )

            new_leads = leads_data.get(
                "new_leads",
                0,
            )

            pending_followups = followups_data.get(
                "pending_followups",
                [],
            )

            customers = customers_data.get(
                "customers",
                [],
            )

            total_orders = orders_data.get(
                "total_orders",
                0,
            )

            pending_orders = orders_data.get(
                "pending_orders",
                0,
            )

            message = (
                "Here is a more detailed view of the "
                "current sales status:\n"
                f"- {total_leads} total leads, "
                f"including {new_leads} new leads.\n"
                f"- {len(pending_followups)} pending follow-ups.\n"
                f"- {len(customers)} customers.\n"
                f"- {total_orders} total orders, "
                f"of which {pending_orders} are pending."
            )

            data = {
                "total_leads": total_leads,
                "new_leads": new_leads,
                "pending_followups": pending_followups,
                "customers": customers,
                "total_orders": total_orders,
                "pending_orders": pending_orders,
            }

            return {
                "agent": self.name,
                "status": "success",
                "data": data,
                "message": message,
            }

        # =====================================================
        # CONTEXTUAL NEW LEADS
        # =====================================================

        if is_more_request and contextual_topic == "leads":

            result = self.crm_tool.execute(
                "get_leads",
                user,
            )

            if result.get("status") == "success":

                data = result.get(
                    "data",
                    {},
                )

                total_leads = data.get(
                    "total_leads",
                    0,
                )

                new_leads = data.get(
                    "new_leads",
                    0,
                )

                message = (
                    f"The CRM currently has {total_leads} leads, "
                    f"including {new_leads} new leads. "
                    "Individual lead names and details are not "
                    "currently available in the CRM response, "
                    "so I can't provide a lead-by-lead breakdown yet."
                )

                return {
                    "agent": self.name,
                    "status": "success",
                    "data": data,
                    "message": message,
                }

        # =====================================================
        # CONTEXTUAL PENDING FOLLOW-UPS
        # =====================================================

        if is_more_request and contextual_topic == "followups":

            result = self.crm_tool.execute(
                "get_pending_followups",
                user,
            )

            if result.get("status") == "success":

                data = result.get(
                    "data",
                    {},
                )

                followups = data.get(
                    "pending_followups",
                    [],
                )

                if not followups:

                    message = "There are currently no pending " "sales follow-ups."

                else:

                    followup_lines = []

                    for followup in followups:

                        customer = followup.get(
                            "customer",
                            "Unknown customer",
                        )

                        days_pending = followup.get(
                            "days_pending",
                            0,
                        )

                        followup_lines.append(
                            f"{customer}: " f"{days_pending} days pending"
                        )

                    message = (
                        "Here are the current pending "
                        "sales follow-ups:\n" + "\n".join(followup_lines)
                    )

                return {
                    "agent": self.name,
                    "status": "success",
                    "data": data,
                    "message": message,
                }

        # =====================================================
        # CONTEXTUAL PENDING ORDERS
        # =====================================================

        if is_more_request and contextual_topic == "orders":

            result = self.crm_tool.execute(
                "get_pending_orders",
                user,
            )

            if result.get("status") == "success":

                data = result.get(
                    "data",
                    {},
                )

                orders = data.get(
                    "orders",
                    [],
                )

                if not orders:

                    message = "There are currently no pending orders."

                else:

                    order_lines = []

                    for order in orders:

                        order_id = order.get(
                            "order_id",
                            "Unknown order",
                        )

                        customer = order.get(
                            "customer",
                            "Unknown customer",
                        )

                        amount = order.get(
                            "amount",
                            0,
                        )

                        status = order.get(
                            "status",
                            "Pending",
                        )

                        order_lines.append(
                            f"{order_id} - "
                            f"{customer} - "
                            f"₹{amount} - "
                            f"{status}"
                        )

                    message = (
                        "Here are the pending orders "
                        "discussed previously:\n" + "\n".join(order_lines)
                    )

                return {
                    "agent": self.name,
                    "status": "success",
                    "data": data,
                    "message": message,
                }

        # =====================================================
        # CONTEXTUAL CUSTOMERS
        # =====================================================

        if is_more_request and contextual_topic == "customers":

            result = self.crm_tool.execute(
                "get_customers",
                user,
            )

            if result.get("status") == "success":

                data = result.get(
                    "data",
                    {},
                )

                customers = data.get(
                    "customers",
                    [],
                )

                if not customers:

                    message = (
                        "There are currently no customers " "available in the CRM."
                    )

                else:

                    customer_lines = []

                    for customer in customers:

                        name = customer.get(
                            "name",
                            "Unknown customer",
                        )

                        status = customer.get(
                            "status",
                            None,
                        )

                        if status:

                            customer_lines.append(f"{name} - {status}")

                        else:

                            customer_lines.append(name)

                    message = (
                        "Here are the customers currently "
                        "available in the CRM:\n" + "\n".join(customer_lines)
                    )

                return {
                    "agent": self.name,
                    "status": "success",
                    "data": data,
                    "message": message,
                }

        # =====================================================
        # GENERAL SALES REQUEST
        # =====================================================

        is_general_sales_request = (
            "sales" in current_question
            or "sale" in current_question
            or "sales status" in current_question
            or "sales summary" in current_question
            or "sales overview" in current_question
            or "current sales" in current_question
            or "sales information" in current_question
            or "revenue" in current_question
        )

        if is_general_sales_request:

            leads_result = self.crm_tool.execute(
                "get_leads",
                user,
            )

            followups_result = self.crm_tool.execute(
                "get_pending_followups",
                user,
            )

            customers_result = self.crm_tool.execute(
                "get_customers",
                user,
            )

            orders_result = self.crm_tool.execute(
                "get_orders",
                user,
            )

            leads_data = (
                leads_result.get("data", {})
                if leads_result.get("status") == "success"
                else {}
            )

            followups_data = (
                followups_result.get("data", {})
                if followups_result.get("status") == "success"
                else {}
            )

            customers_data = (
                customers_result.get("data", {})
                if customers_result.get("status") == "success"
                else {}
            )

            orders_data = (
                orders_result.get("data", {})
                if orders_result.get("status") == "success"
                else {}
            )

            total_leads = leads_data.get(
                "total_leads",
                0,
            )

            new_leads = leads_data.get(
                "new_leads",
                0,
            )

            pending_followups = followups_data.get(
                "pending_followups",
                [],
            )

            customers = customers_data.get(
                "customers",
                [],
            )

            total_orders = orders_data.get(
                "total_orders",
                0,
            )

            pending_orders = orders_data.get(
                "pending_orders",
                0,
            )

            message = (
                "Current sales summary: "
                f"{total_leads} total leads, "
                f"{new_leads} new leads, "
                f"{len(pending_followups)} pending follow-ups, "
                f"{len(customers)} customers, "
                f"{total_orders} total orders, "
                f"{pending_orders} pending orders."
            )

            data = {
                "total_leads": total_leads,
                "new_leads": new_leads,
                "pending_followups": pending_followups,
                "customers": customers,
                "total_orders": total_orders,
                "pending_orders": pending_orders,
            }

            return {
                "agent": self.name,
                "status": "success",
                "data": data,
                "message": message,
            }

        # =====================================================
        # PENDING FOLLOW-UPS
        # =====================================================

        if (
            "follow-up" in current_question
            or "follow up" in current_question
            or "followups" in current_question
        ):

            result = self.crm_tool.execute(
                "get_pending_followups",
                user,
            )

            if result.get("status") == "success":

                data = result.get(
                    "data",
                    {},
                )

                followups = data.get(
                    "pending_followups",
                    [],
                )

                if not followups:

                    message = "There are no pending follow-ups."

                else:

                    followup_lines = []

                    for followup in followups:

                        customer = followup.get(
                            "customer",
                            "Unknown customer",
                        )

                        days_pending = followup.get(
                            "days_pending",
                            0,
                        )

                        followup_lines.append(
                            f"{customer}: " f"{days_pending} days pending"
                        )

                    message = (
                        f"There are currently "
                        f"{len(followups)} customers "
                        "requiring follow-up:\n" + "\n".join(followup_lines)
                    )

                return {
                    "agent": self.name,
                    "status": "success",
                    "data": data,
                    "message": message,
                }

        # =====================================================
        # LEADS
        # =====================================================

        if "lead" in current_question:

            result = self.crm_tool.execute(
                "get_leads",
                user,
            )

            if result.get("status") == "success":

                data = result.get(
                    "data",
                    {},
                )

                message = (
                    f"There are "
                    f"{data.get('total_leads', 0)} "
                    "total leads, including "
                    f"{data.get('new_leads', 0)} "
                    "new leads."
                )

                return {
                    "agent": self.name,
                    "status": "success",
                    "data": data,
                    "message": message,
                }

        # =====================================================
        # CUSTOMERS
        # =====================================================

        if "customer" in current_question:

            result = self.crm_tool.execute(
                "get_customers",
                user,
            )

            if result.get("status") == "success":

                data = result.get(
                    "data",
                    {},
                )

                customers = data.get(
                    "customers",
                    [],
                )

                if not customers:

                    message = "There are no customers in the CRM."

                else:

                    customer_names = [
                        customer.get(
                            "name",
                            "Unknown customer",
                        )
                        for customer in customers
                    ]

                    message = (
                        f"There are {len(customers)} "
                        "customers: " + ", ".join(customer_names) + "."
                    )

                return {
                    "agent": self.name,
                    "status": "success",
                    "data": data,
                    "message": message,
                }

        # =====================================================
        # ORDERS
        # =====================================================

        if "order" in current_question:

            # ------------------------------------------
            # Pending Orders
            # ------------------------------------------

            if "pending" in current_question:

                result = self.crm_tool.execute(
                    "get_pending_orders",
                    user,
                )

                if result.get("status") == "success":

                    data = result.get(
                        "data",
                        {},
                    )

                    orders = data.get(
                        "orders",
                        [],
                    )

                    if not orders:

                        message = "There are no pending orders."

                    else:

                        order_lines = []

                        for order in orders:

                            order_lines.append(
                                f"{order.get('order_id', 'Unknown order')} - "
                                f"{order.get('customer', 'Unknown customer')} - "
                                f"₹{order.get('amount', 0)}"
                            )

                        message = (
                            f"There are {len(orders)} "
                            "pending orders:\n" + "\n".join(order_lines)
                        )

                    return {
                        "agent": self.name,
                        "status": "success",
                        "data": data,
                        "message": message,
                    }

            # ------------------------------------------
            # All Orders
            # ------------------------------------------

            else:

                result = self.crm_tool.execute(
                    "get_orders",
                    user,
                )

                if result.get("status") == "success":

                    data = result.get(
                        "data",
                        {},
                    )

                    total_orders = data.get(
                        "total_orders",
                        0,
                    )

                    pending_orders = data.get(
                        "pending_orders",
                        0,
                    )

                    message = (
                        f"There are {total_orders} "
                        "total orders, including "
                        f"{pending_orders} "
                        "pending orders."
                    )

                    return {
                        "agent": self.name,
                        "status": "success",
                        "data": data,
                        "message": message,
                    }

        # =====================================================
        # UNSUPPORTED REQUEST
        # =====================================================

        return {
            "agent": self.name,
            "status": "error",
            "data": {},
            "message": (
                "The requested sales information " "is not currently supported."
            ),
        }
